version: '2'
services:
    jenkins:
        # image: jeffersonsouza/jenkins:alpine
        build:
          context: ./
          dockerfile: Dockerfile
        privileged: true
        restart: always
        ports:
            - "8085:8080"
            - "50000:50000"
        volumes:
            - ./jenkins-data:/var/jenkins_home/
            ## - /var/run/docker.sock:/var/run/docker.sock
    # node:
    #     # image: jeffersonsouza/jenkins:slave-node
    #     build:
    #       context: ./node-slave
    #       dockerfile: Dockerfile
    #     privileged: true
    #     ports:
    #         - 22
    #     volumes_from:
    #         - jenkins
    # php:
    #     # image: jeffersonsouza/jenkins:slave-php
    #     build:
    #       context: ./php-slave
    #       dockerfile: Dockerfile
    #     privileged: true
    #     ports:
    #         - 22
    #     volumes_from:
    #         - jenkins
    # php56:
    #     # image: jeffersonsouza/jenkins:slave-php5
    #     build:
    #       context: ./php56-slave
    #       dockerfile: Dockerfile
    #     privileged: true
    #     ports:
    #         - 22
    #     volumes_from:
    #         - jenkins
    dotnetcore:
        build:
          context: ./dotnetcore-slave
          dockerfile: Dockerfile
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
volumes:
    jenkins-data:
        driver: local
